### ISSUE TITLE
Project export in export format "Auto" crashes, works in other export format(s)

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#100]
Project export in export format set to "Auto" doesn't finish. It gets stuck at 90% with error dumps. This happens just after finishing exporting constraint files (which is successful).

Stack trace
```
2015-09-06 02:07:52  INFO [Thread-5] [admin] (RepositoryServiceDbData) - Exported constraints set file [15.txt] for project [kp3_test_2703] with ID [1]
2015-09-06 02:07:52  INFO [Thread-5] [admin] (RepositoryServiceDbData) - Upgraded CAS of user [CURATION_USER] for document [webanno_examples_20150410_lemmatized.xmi]  in project ID [1]
2015-09-06 02:07:52 ERROR [Thread-5] [admin] (PrimitiveAnalysisEngine_impl) - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException: Trying to access value of feature "webanno.custom.SemPred:RoleSet" as "webanno.custom.SemPredRoleSetLink[]", but range of feature is "{2}".
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.process(WebannoCustomTsvWriter.java:105)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:229)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.exportAnnotationDocument(RepositoryServiceDbData.java:654)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.exportAnnotationDocument(RepositoryServiceDbData.java:558)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy44.exportAnnotationDocument(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:480)
	at com.sun.proxy.$Proxy52.exportAnnotationDocument(Unknown Source)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel.exportCuratedDocuments(ProjectExportPanel.java:212)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel.access$2(ProjectExportPanel.java:172)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel$FileGenerator.generateZipFile(ProjectExportPanel.java:509)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel$FileGenerator.run(ProjectExportPanel.java:464)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.uima.cas.CASRuntimeException: Trying to access value of feature "webanno.custom.SemPred:RoleSet" as "webanno.custom.SemPredRoleSetLink[]", but range of feature is "{2}".
	at org.apache.uima.cas.impl.CASImpl.getFeatureValueAsString(CASImpl.java:2327)
	at org.apache.uima.cas.impl.FeatureStructureImpl.getFeatureValueAsString(FeatureStructureImpl.java:354)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.setTokenAnnos(WebannoCustomTsvWriter.java:362)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.convertToTsv(WebannoCustomTsvWriter.java:230)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.process(WebannoCustomTsvWriter.java:102)
	... 33 more
2015-09-06 02:07:52 ERROR [Thread-5] [admin] (AggregateAnalysisEngine_impl) - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException: Trying to access value of feature "webanno.custom.SemPred:RoleSet" as "webanno.custom.SemPredRoleSetLink[]", but range of feature is "{2}".
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.process(WebannoCustomTsvWriter.java:105)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:229)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.exportAnnotationDocument(RepositoryServiceDbData.java:654)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.exportAnnotationDocument(RepositoryServiceDbData.java:558)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy44.exportAnnotationDocument(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:480)
	at com.sun.proxy.$Proxy52.exportAnnotationDocument(Unknown Source)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel.exportCuratedDocuments(ProjectExportPanel.java:212)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel.access$2(ProjectExportPanel.java:172)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel$FileGenerator.generateZipFile(ProjectExportPanel.java:509)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel$FileGenerator.run(ProjectExportPanel.java:464)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.uima.cas.CASRuntimeException: Trying to access value of feature "webanno.custom.SemPred:RoleSet" as "webanno.custom.SemPredRoleSetLink[]", but range of feature is "{2}".
	at org.apache.uima.cas.impl.CASImpl.getFeatureValueAsString(CASImpl.java:2327)
	at org.apache.uima.cas.impl.FeatureStructureImpl.getFeatureValueAsString(FeatureStructureImpl.java:354)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.setTokenAnnos(WebannoCustomTsvWriter.java:362)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.convertToTsv(WebannoCustomTsvWriter.java:230)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.process(WebannoCustomTsvWriter.java:102)
	... 33 more
2015-09-06 02:07:52 ERROR [Thread-5] [admin] (ProjectPage) - Unexpected error during project export
org.apache.uima.analysis_engine.AnalysisEngineProcessException: Trying to access value of feature "webanno.custom.SemPred:RoleSet" as "webanno.custom.SemPredRoleSetLink[]", but range of feature is "{2}".
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.process(WebannoCustomTsvWriter.java:105)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:229)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.exportAnnotationDocument(RepositoryServiceDbData.java:654)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.exportAnnotationDocument(RepositoryServiceDbData.java:558)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy44.exportAnnotationDocument(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:480)
	at com.sun.proxy.$Proxy52.exportAnnotationDocument(Unknown Source)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel.exportCuratedDocuments(ProjectExportPanel.java:212)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel.access$2(ProjectExportPanel.java:172)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel$FileGenerator.generateZipFile(ProjectExportPanel.java:509)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel$FileGenerator.run(ProjectExportPanel.java:464)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.uima.cas.CASRuntimeException: Trying to access value of feature "webanno.custom.SemPred:RoleSet" as "webanno.custom.SemPredRoleSetLink[]", but range of feature is "{2}".
	at org.apache.uima.cas.impl.CASImpl.getFeatureValueAsString(CASImpl.java:2327)
	at org.apache.uima.cas.impl.FeatureStructureImpl.getFeatureValueAsString(FeatureStructureImpl.java:354)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.setTokenAnnos(WebannoCustomTsvWriter.java:362)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.convertToTsv(WebannoCustomTsvWriter.java:230)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsvWriter.process(WebannoCustomTsvWriter.java:102)
	... 33 more
```

**Comment by reckart** [comment]
Yes, that happens if the data cannot be written in the selected format. E.g. the TsvWriter does afaik not yet support link features.

The correct behavior should probably be to catch the exception, to abort the export process, and to display a proper error message.

**Comment by reckart** [comment]
... or to skip the files that cannot be exported and also display a proper error message.

**Comment by aakashysharma** [comment]
I'm not sure if skipping certain things would help when it's imported back into webanno. I made fix to catch exceptions and post error messages in logger.

**Comment by reckart** [comment]
For importing, it makes no difference. Actually the export always exports two formats: 1) the internal serialized CAS format and 2) the format that the user selects from the dropdown. For import, only 1) the internal CAS format files are used.

**Comment by reckart** [comment]
Are the error messages visible to the user or only in the log? They should be visible in the feedback panel in the UI.

**Comment by aakashysharma** [comment]
In log. There are two loops which are causing the exception in TsvWriter. So the fix, is inside those loops catches exception and writes to log.

**Comment by reckart** [comment]
The TSV writer should not ignore such problems. It should throw an exception with a proper error message. WebAnno should catch that message and display it to the user. The only question then is whether it WebAnno (not the TsvWriter) should skip the file or not.

Please update TsvWriter to fail properly and WebAnno to properly handle failures of the writer and display them to the user. The safe option would be to fail the export if a write fails.

**Comment by reckart** [comment]
@ChrisBieTUDA  @seyyaw FYI because this is TSV code.

**Comment by aakashysharma** [comment]
Reverted earlier fix to approach in a different way.

**Comment by MeDarina** [comment]
The project export gets stuck at 10% now, without any error message. The same happens if you try to export in "WebAnno TSV Format" directly.

**Comment by aakashysharma** [comment]
@MeDarina In the meantime, I'd suggest you to use other format such as "binary" for export.
