### ISSUE TITLE
webanno crashes

### ISSUE THREAD

**Issue by gpythomas** [webanno/webanno#1040]
The war version of WebAnno 3.4.5 keeps crashing on my server (Ubuntu Linux 16.04.2). I have followed the installation instructions available in the [admin-guide](https://webanno.github.io/[webanno/releases/3.4.5/docs/admin-guide.html) to deploy WebAnno in a separare Tomcat instance. After deploying the app I can access it online (with Chrome) and all its functionalities seem to be available, but it crashes after about five minutes of use. The application freezes and goes offline (refreshing the browser gets me a ERR_CONNECTION_REFUSED). Then I have to restart WebAnno to get it working again.

I'm not sure how to interpret the WebAnno logs but /opt/webanno/log/catalina.out reports the following error:

`Aug 17, 2018 5:40:50 PM org.apache.catalina.startup.ContextConfig processAnnotationsJar
SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/opt/webanno/webapps/webanno/WEB-INF/lib/jaxb-api-2.3.0.jar!/] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
        at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97)
        at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:55)
        at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:176)
        at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:85)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2035)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1981)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1951)
        at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1905)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1148)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:770)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:305)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5163)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by seyyaw** [comment]
@gpythomas It looks there is some version mismatch between your java and tomcat installations. What are the versions you are running?

**Comment by gpythomas** [comment]
Hello @seyyaw, here is the output of java -version:

`openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)`

And here is the output of version.sh:

`Using CATALINA_BASE:   /opt/tomcat
Using CATALINA_HOME:   /opt/tomcat
Using CATALINA_TMPDIR: /opt/tomcat/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /opt/tomcat/bin/bootstrap.jar:/opt/tomcat/bin/tomcat-juli.jar
Server version: Apache Tomcat/8.5.31
Server built:   Apr 27 2018 20:24:25 UTC
Server number:  8.5.31.0
OS Name:        Linux
OS Version:     2.6.32-042stab120.19
Architecture:   amd64
JVM Version:    1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13
JVM Vendor:     Oracle Corporation`

**Comment by reckart** [comment]
> Aug 17, 2018 5:40:50 PM org.apache.catalina.startup.ContextConfig processAnnotationsJar SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/opt/webanno/webapps/webanno/WEB-INF/lib/jaxb-api-2.3.0.jar!/] for annotations org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19 at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97) at 

Another user with the same problem found out that there were actually two different versions
of tomcat installed, (one 8.0.x in /usr/share and one 8.5.x in /opt) and that WebAnno had been deployed
into the wrong one (i.e. the 8.0.x one).

Please check that WebAnno is *really* running in a Tomcat 8.5.x version. 

Check the log file containing the error message (not `version.sh`) as it should tell you the Tomcat version somewhere shortly before the WebAnno startup log lines.

**Comment by gpythomas** [comment]
Yes, you're right, the logs indicates that WebAnno is running tomcat 8.0.32, while the version of Tomcat that is installed in /opt/tomcat is 8.5.31.0. I assume this due to the version of my tomcat8-user? I followed the installation instructions for runnin WebAnno via separate Tomcat, which creates a user instance of Tomcat. But the most recent tomcat8-user package on ubuntu0.16.04 (my server OS) appears to be 8.0.32, and it's the one that I have installed. Debian has a packaged 8.5.32 version. Do you recommend updating tomcat8-user and reinstalling WebAnno?

**Comment by reckart** [comment]
@gpythomas I would recommend using the JAR version of WebAnno which comes with an embedded Tomcat - so no need to maintain a separate Tomcat installation. This JAR is based on Spring Boot and can be conveniently installed as a UNIX system service. For some time already, I have migrated all my WebAnno installations use the JAR version (of course still in conjunction with a MySQL DB).

**Comment by gpythomas** [comment]
Thanks, I switched to the JAR version and everything seems to run fine. One remaining question is how to set up SSL for WebAnno's port (18080) with this option. Should I make it run behing Apache and configure SSL in Apache?

**Comment by gpythomas** [comment]
Hello, I'm sorry for all the questions, but now the JAR version of WebAnno has started displaying an error message upon login:

"""
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sun Sep 09 21:34:10 EDT 2018
There was an unexpected error (type=Not Found, status=404).
No message available
"""
I can't find any log to consult in /srv/webanno, and I'm not sure what triggered this error, since I didn't change the configuration. Do you have any suggestions?

**Comment by reckart** [comment]
That is a `404 Not found` error meaning that you are trying to access a URL that is not served by the application. When you switch from the WAR to the JAR version, the URL of WebAnno usually changes. The WAR version is usually deployed in such a way that it is reachable under `http://host:port/webanno/` while the default for the JAR version is `http://host:port/`. If you are additionally running the JAR version behind a reverse-proxy, then there may be a mismatch between the proxy configuration expecting the application under `http://host:port/webanno/` and the JAR version serving the application under `http://host:port/`, causing the application not to be reachable anymore at all under neither of the URLs.

To fix this reverse-proxy situation and/or to change the URL under which the application is served, you can add a few additional lines to the `settings.properties` file, e.g. 

```
server.contextPath=/webanno
server.use-forward-headers=true
```

For more information, see https://webanno.github.io/webanno/releases/3.4.5/docs/admin-guide.html#_running_the_standalone_behind_httpd
