### ISSUE TITLE
Rendering Terminated due to: IndexSizeError 

### ISSUE THREAD

**Issue by adindabudi** [webanno/webanno#1046]
[screenshot](https://drive.google.com/file/d/1N87xMHh2xLEbDIuHf9YCiEaneB4exZTS/view?usp=sharing)

Got this error when open console:
`Rendering terminated due to: IndexSizeError: Failed to execute 'getEndPositionOfChar' on 'SVGTextContentElement': The charnum provided (510) is greater than or equal to the maximum bound (510). Error: Failed to execute 'getEndPositionOfChar' on 'SVGTextContentElement': The charnum provided (510) is greater than or equal to the maximum bound (510).
    at http://localhost:8080/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-3D0C7B79236B74F63447EE986A21972A.js:1346:8
    at Fragment.<anonymous> (http://localhost:8080/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-3D0C7B79236B74F63447EE986A21972A.js:1165:1)
    at Function.each (http://localhost:8080/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.2.4-ver-F9EE266EF993962AD59E804AD9DEBE66.js:2:2861)
    at SVGTextElement.<anonymous> (http://localhost:8080/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-3D0C7B79236B74F63447EE986A21972A.js:1164:3)
    at Function.each (http://localhost:8080/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.2.4-ver-F9EE266EF993962AD59E804AD9DEBE66.js:2:2861)
    at a.fn.init.each (http://localhost:8080/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.2.4-ver-F9EE266EF993962AD59E804AD9DEBE66.js:2:845)
    at getTextMeasurements (http://localhost:8080/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-3D0C7B79236B74F63447EE986A21972A.js:1160:34)
    at getTextAndSpanTextMeasurements (http://localhost:8080/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-3D0C7B79236B74F63447EE986A21972A.js:1188:17)
    at renderDataReal (http://localhost:8080/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-3D0C7B79236B74F63447EE986A21972A.js:1527:13)
    at http://localhost:8080/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-3D0C7B79236B74F63447EE986A21972A.js:3344:1`

**Comment by reckart** [comment]
@adindabudi Which version of WebAnno are you using? Is this LTR or RTL script? Does the problem happen directly after importing an unannotated text or only after annotation?

**Comment by adindabudi** [comment]
version 3.4.5 and LTR. yes, it happens after importing TSV Webanno file.

**Comment by reckart** [comment]
Did you create the TSV file yourself or is it a file exported from WebAnno (if exported, from which version of WebAnno)?

**Comment by adindabudi** [comment]
I created TSV file myself using python.

**Comment by reckart** [comment]
In that case, please check that all your tokens are within sentences, that the sentence boundaries match the boundaries of the first and last token in the sentence, and that annotations all start/end either at token boundaries or within tokens, but not at some position between tokens or between sentences. 

For curiosity: are you using some third-party library to generate WebAnno TSV or did you write all the code yourself?

You may also try applying the "CAS Doctor" to your file to check for common problems (note that CAS Doctor does not check all the points that I mentioned above). You can find the CAS doctor tab in the project settings.

**Comment by reckart** [comment]
No further feedback - assuming this one has been resolved.
