### ISSUE TITLE
Crossing sentence bounardies is not permitted

### ISSUE THREAD

**Issue by rgsol** [webanno/webanno#1196]
We just upgraded from 3.4.5 to 3.5.0. Now we see the exception below and a corresponding error in the user interface if we try to finish a curated document. We already saw such exceptions in 3.4.5 too but only in the logs and they didn't prevent the curator from finishing the documents.

```
2019-01-22 15:00:06 ERROR [xyzuser] CurationPage - Error: Document cannot be marked as finished. Annotation with ID [5864] on layer [Token] is invalid: Crossing sentence bounardies is not permitt
ed.
java.lang.IllegalStateException: Document cannot be marked as finished. Annotation with ID [5864] on layer [Token] is invalid: Crossing sentence bounardies is not permitted.
        at de.tudarmstadt.ukp.clarin.webanno.ui.annotation.AnnotationPageBase.actionValidateDocument(AnnotationPageBase.java:418) ~[webanno-ui-annotation-3.5.0.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.ui.curation.page.CurationPage.lambda$actionFinishDocument$c8c06b0d$1(CurationPage.java:567) ~[webanno-ui-curation-3.5.0.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.support.dialog.ConfirmationDialog.onConfirmInternal(ConfirmationDialog.java:174) ~[webanno-support-3.5.0.jar!/:?]
        at de.tudarmstadt.ukp.clarin.webanno.support.lambda.LambdaAjaxButton.onSubmit(LambdaAjaxButton.java:52) [webanno-support-3.5.0.jar!/:?]
        at org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:113) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:223) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1271) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.markup.html.form.Form.process(Form.java:964) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:788) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:176) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:127) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:598) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.core.request.handler.ListenerRequestHandler.internalInvoke(ListenerRequestHandler.java:306) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.core.request.handler.ListenerRequestHandler.invoke(ListenerRequestHandler.java:280) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.core.request.handler.ListenerRequestHandler.invokeListener(ListenerRequestHandler.java:222) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.core.request.handler.ListenerRequestHandler.respond(ListenerRequestHandler.java:208) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:912) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:65) [wicket-request-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:283) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:253) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:221) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:262) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:204) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:286) [wicket-core-8.1.0.jar!/:8.1.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:185) [spring-orm-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.1.3.RELEASE.jar!/:5.1.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at de.tudarmstadt.ukp.clarin.webanno.support.logging.LoggingFilter.doFilter(LoggingFilter.java:52) [webanno-support-3.5.0.jar!/:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82) [spring-security-web-4.2.10.RELEASE.jar!/:4.2.10.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.35.jar!/:8.5.35]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) [spring-security-web-4.2.10.RELEASE.jar!/:4.2.10.RELEASE]
...
```

**Comment by reckart** [comment]
@rgsol That looks to me as if your data is defective. I have tested on my installation and marking documents as finished there is no problem. 

WebAnno expects that all tokens are contained in sentences and that the sentence boundaries coincide with token boundaries. Anything different is invalid data and may lead to unexpected problems.

What source format does your data have (i.e. which was the original format used when importing the data)?

**Comment by rgsol** [comment]
@reckart The original data is plain text. We already tried to figure out if there are tokens that cross sentence boundaries but couldn't find any. We'll further investigate and prepare an example soon.

**Comment by reckart** [comment]
Thanks. If the data was imported as plaintext, it should be fine unless we have a bug in the tokenizer code. Otherwise, there could be a bug in the validation code. Having an example would be very helpful.

**Comment by rgsol** [comment]
@reckart Small example snippet. What we recognized is that the complaint is always connected to having a single dot (*"."*) treated as a sentence. The problem not only occurs in the curation step but also in the annotation if we try to finish an annotation. No clue why the dot is separated. In the text it's properly attached to the sentence. As already mentioned we saw this error in 3.4.5 too but only in the logs and it didn't prevent people from finishing.

This is the error message

![webanno-2019-01-23-screenshot01](https://user-images.githubusercontent.com/46931894/51603838-38d38b80-1f0b-11e9-86e7-3b7b880ef96d.png)

This is the curation page before we try to finish, here with a litle more context

![webanno-2019-01-23-screenshot02](https://user-images.githubusercontent.com/46931894/51603848-438e2080-1f0b-11e9-9fab-7942e6b927ba.png)

And that's the corresponding text

[text-example.txt](https://github.com/webanno/webanno/files/2787064/text-example.txt)

**Comment by rgsol** [comment]
@reckart What I said about seeing this error in 3.4.5 already might not be true. I was relying on a colleague and couln't prove it myself. Sorry if that caused some confusion.

**Comment by rgsol** [comment]
@reckart I was fiddling around with the snippet from above. If I slightly modify it by removing a newline between the two first paragraphs then it fails again with the "dot" issue, but now having the single-dot-sentence  in a different location

[test02.txt](https://github.com/webanno/webanno/files/2788142/test02.txt)

**Comment by rgsol** [comment]
I think I know what the problem is: it is assumed that a new sentence always starts with a letter. The trouble arises if there is something else. Special characters in conjunction with newlines produce such "single-dot-sentences" and those lead to the error. Here is my constructed example. If you import it into webanno you'll immediately see what happens.

[test05.txt](https://github.com/webanno/webanno/files/2788287/test05.txt)

**Comment by reckart** [comment]
Thanks. I'll look into it. It seems like it could be a pretty critical bug that might warrant a 3.5.1 release.

**Comment by reckart** [comment]
We know that the sentence detector is imperfect - and this is "ok" at the moment because we simply use the Java BreakIterator here. It is presently expected that users who require a more sophisticated sentence splitting or tokenizing perform this externally and then import pre-tokenized/sentence-split text e.g. in TSV format. 

However, if the internal tokenizer/sentence splitter code generates tokens which cross sentence boundaries or if the code which tries to detect annotations illegally crossing sentence boundaries are bad, then this is a bug that needs to be fixed.

**Comment by reckart** [comment]
From a first glance, I would guess he validation code has a bug because export in TSV3 format works and normally I would expect that to fail if there was a cross-sentence token. But I'll need to dig in further.

**Comment by rgsol** [comment]
@reckart Thanks. We know that sentence splitting can be tricky so we don't expect it to be perfect at all. If the validation could deal with a single-dot-sentence in some way that would be ok. We have quite a lot of documents that contain such cases.

**Comment by reckart** [comment]
Ok, this is should be fixed now along with a rendering bug which had a similar cause.
