### ISSUE TITLE
Monitoring page error

### ISSUE THREAD

**Issue by zhangxieyang2** [webanno/webanno#1328]
**Describe the bug**
I can't access the monitoring page. It is redirected to an error page. ( It seems the other pages, including Annotation, Curation, Agreement, Projects and Users, are working fine. )

**To Reproduce**
1. I have imported an example project (Unicode example project)
2. Go to home page (as a project manager or curator)
2. Click on Monitoring
4. The it comes the error page, showing 
![image](https://user-images.githubusercontent.com/9495933/58686349-300b2e80-83b1-11e9-8647-2b6b565f6762.png)

**Please complete the following information:**

 - OS: [the server is on Ubuntu 14.04, and the browser is on Windows]
 - Browser: [chrome]

How should I fix it? Thank you very much.

**This is error message of stack trace**

2019-05-31 14:30:33 ERROR [SYSTEM] ErrorPageFilter - Forwarding to error page from request [/monitoring.html] due to exception [Filter execution threw an exception]
javax.servlet.ServletException: Filter execution threw an exception
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:200) ~[catalina.jar:8.5.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.41]
        at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:185) ~[spring-orm-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.3.RELEASE.jar:5.1.3.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.41]
        at de.tudarmstadt.ukp.clarin.webanno.support.logging.LoggingFilter.doFilter(LoggingFilter.java:52) ~[webanno-support-3.5.6.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.41]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.41]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.41]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.41]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.41]
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.41]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[catalina.jar:8.5.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[catalina.jar:8.5.41]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) ~[spring-security-web-4.2.10.RELEASE.jar:4.2.10.RELEASE]

**Comment by reckart** [comment]
Which WebAnno version are you using?

**Comment by zhangxieyang2** [comment]
> Which WebAnno version are you using?

I'm using 3.5.6
And I found two error messages that may closely related to webanno just now.

at de.tudarmstadt.ukp.clarin.webanno.support.logging.LoggingFilter.doFilter(LoggingFilter.java:52) ~[webanno-support-3.5.6.jar:?]    
at de.tudarmstadt.ukp.clarin.webanno.support.jfreechart.SvgChart.renderSvg(SvgChart.java:113) ~[webanno-support-3.5.6.jar:?]

Thank you!

**Comment by reckart** [comment]
So it seems the error happens when the system is trying to draw the progress charts on that page. 

Can you see more lines of the stack trace below the SvgChart line?

**Comment by zhangxieyang2** [comment]
> So it seems the error happens when the system is trying to draw the progress charts on that page.
> 
> Can you see more lines of the stack trace below the SvgChart line?

The lines around the SvgChart are as follows:


at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_101]
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103) ~[?:1.8.0_101]
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82) ~[?:1.8.0_101]
        at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181) ~[?:1.8.0_101]
        at org.apache.batik.svggen.SVGGraphics2D.<init>(SVGGraphics2D.java:154) ~[batik-svggen-1.9.1.jar:?]
        at org.apache.batik.svggen.SVGGraphics2D.<init>(SVGGraphics2D.java:263) ~[batik-svggen-1.9.1.jar:?]
        at de.tudarmstadt.ukp.clarin.webanno.support.jfreechart.SvgChart.renderSvg(SvgChart.java:113) ~[webanno-support-3.5.6.jar:?]
        at org.apache.wicket.model.LoadableDetachableModel$1.load(LoadableDetachableModel.java:216) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:128) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.getDefaultModelObject(Component.java:1574) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.getDefaultModelObjectAsString(Component.java:1602) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.markup.html.basic.Label.onComponentTagBody(Label.java:115) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.internalRenderComponent(Component.java:2484) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.markup.html.WebComponent.onRender(WebComponent.java:60) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.internalRender(Component.java:2289) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.render(Component.java:2220) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1454) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1654) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1629) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:798) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:77) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.internalRenderComponent(Component.java:2484) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1593) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.internalRender(Component.java:2289) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.render(Component.java:2220) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1454) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1654) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1629) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1587) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.internalRenderComponent(Component.java:2484) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1593) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.internalRender(Component.java:2289) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.render(Component.java:2220) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1454) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1654) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Page.onRender(Page.java:858) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:126) ~[wicket-core-8.3.0.jar:8.3.0]
        at org.apache.wicket.Component.internalRender(Component.java:2289) ~[wicket-core-8.3.0.jar:8.3.0]

**Comment by reckart** [comment]
What Java Runtime are you running on? Do you have support for a graphical desktop environment installed? While WebAnno can run in a headless environment, the charts code needs to be able to activate the Java AWT subsystem to do the server-side rendering of the charts.

**Comment by zhangxieyang2** [comment]
> What Java Runtime are you running on? Do you have support for a graphical desktop environment installed? While WebAnno can run in a headless environment, the charts code needs to be able to activate the Java AWT subsystem to do the server-side rendering of the charts.

The java version is as follows
![image](https://user-images.githubusercontent.com/9495933/58701061-7a51d700-83d4-11e9-9027-88ffa74a787a.png)
I will try to search according to your tips and see whether it can be solves. 
Thank you!

**Comment by zhangxieyang2** [comment]
> What Java Runtime are you running on? Do you have support for a graphical desktop environment installed? While WebAnno can run in a headless environment, the charts code needs to be able to activate the Java AWT subsystem to do the server-side rendering of the charts.

Thank you for your kink reply.
I have solved this problem by adding the following line to ```catalina.sh``` of tomcat.
```
CATALINA_OPTS=-Djava.awt.headless=true
```

**Comment by reckart** [comment]
Great :)
