### ISSUE TITLE
No data displayed on annotation console

### ISSUE THREAD

**Issue by bguil** [webanno/webanno#1508]
**Describe the bug**
For some validators and some text, no data appears in the "Annotation" interface. See first screenshot.

**To Reproduce**
Several annotators report the same problem. They were able to annotate one or two documents and then are not able to annotate the next ones.

**Expected behavior**
A text to annotate (see second screenshot: same document with another user)

**Screenshots**

![Image 30-10-2019 at 14 03](https://user-images.githubusercontent.com/687155/67860435-1ddb1b00-fb1e-11e9-9295-74645f55ebc1.jpg)

<img width="1186" alt="normal" src="https://user-images.githubusercontent.com/687155/67860329-d8b6e900-fb1d-11e9-8eaf-7882b8ac15fb.png">

**Please complete the following information:**
 - WebAnno -- 3.6.1 (2019-10-08 18:47:21, build fe9805cd4933573b4442701870387e0e7b09c602)
 - OS: Linux CentOS on the server, Mac OSX on the client (but other clients report the same problem)
 - Browser: Bug with Chrome, Firefox, Brave (seems to work well with Safari)

**Additional context**

Following error message in the javascript console (on Brave):
```

visualizer-ver-2A4F096C6019F64B8AF404DAF2BA03CE.js:3412 Rendering terminated due to: IndexSizeError: Failed to execute 'getEndPositionOfChar' on 'SVGTextContentElement': The charnum provided (3) is greater than or equal to the maximum bound (3). Error: Failed to execute 'getEndPositionOfChar' on 'SVGTextContentElement': The charnum provided (3) is greater than or equal to the maximum bound (3).
    at http://webanno.grew.fr/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-2A4F096C6019F64B8AF404DAF2BA03CE.js:1352:8
    at Fragment.<anonymous> (http://webanno.grew.fr/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-2A4F096C6019F64B8AF404DAF2BA03CE.js:1171:1)
    at Function.each (http://webanno.grew.fr/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.2.4-ver-F9EE266EF993962AD59E804AD9DEBE66.js:2:2861)
    at SVGTextElement.<anonymous> (http://webanno.grew.fr/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-2A4F096C6019F64B8AF404DAF2BA03CE.js:1170:3)
    at Function.each (http://webanno.grew.fr/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.2.4-ver-F9EE266EF993962AD59E804AD9DEBE66.js:2:2861)
    at a.fn.init.each (http://webanno.grew.fr/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.2.4-ver-F9EE266EF993962AD59E804AD9DEBE66.js:2:845)
    at getTextMeasurements (http://webanno.grew.fr/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-2A4F096C6019F64B8AF404DAF2BA03CE.js:1166:34)
    at getTextAndSpanTextMeasurements (http://webanno.grew.fr/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-2A4F096C6019F64B8AF404DAF2BA03CE.js:1194:17)
    at renderDataReal (http://webanno.grew.fr/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-2A4F096C6019F64B8AF404DAF2BA03CE.js:1534:13)
    at http://webanno.grew.fr/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-2A4F096C6019F64B8AF404DAF2BA03CE.js:3405:1
```

**Comment by reckart** [comment]
My guess would be that there might be some odd characters in the documents you are working with - it could also be some bug where token/sentence boundaries are not set properly. 

Could you please go to the "CAS Doctor" tab in the project settings and run the "checks"?

If none of the checks reports any issues, it would be great if you could provide me with one of the documents which fail to render.

**Comment by bguil** [comment]
In the CAS doctor tab, every lines have one of the two messages of the screenshot.
![Image 03-11-2019 at 09 28](https://user-images.githubusercontent.com/687155/68082403-67787e00-fe1c-11e9-9f7f-828ce442d2dd.jpg)

I attach one of the files where the problem exists. I have imported it with the CoNLLU format.
[Alice_EN-200w__10.conllu.txt](https://github.com/webanno/webanno/files/3801356/Alice_EN-200w__10.conllu.txt). At that time, only the POS layer is activated.

With more tests, it seems that everything is ok with Safari and Microsoft Edge and the problem happens with other Browsers: Firefox, Chrome and Brave at least.

**Comment by reckart** [comment]
Your file contains spaces in the tokens - this is not supported by WebAnno. Below you can see that there between the `if` and the `0x09` (tab), there is a `0x20` (space). Please sure that your files do not include spaces with the tokens. Only tabs are field separators in CoNLL-U files - spaces are not.

<img width="1109" alt="2019-11-03_23-25-15" src="https://user-images.githubusercontent.com/1410238/68093005-6a618600-fe91-11e9-8c09-b2cc17b0658d.png">

**Comment by reckart** [comment]
The upstream DKPro Core components might be made more robust against such issues by trimming field values by default.

https://github.com/dkpro/dkpro-core/issues/1422

**Comment by bguil** [comment]
Thanks for your help. I should have been more careful when preparing my data.

I think that an error message or at least a warning at the import step would be more useful than a trimming of the data.
