### ISSUE TITLE
Exception on layers pane if a project defines no layers

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#1525]
**Describe the bug**
If a project defines no layers at all, the layers pane in the project settings bails out with an internal error.

**To Reproduce**
1. Create a fresh project
2. Manually delete all the layer and feature definitions from the database

**Expected behavior**
The pane should show up empty, maybe with a helpful error message.

**Screenshots**
<details>

```
Caused by: javax.persistence.NoResultException: Super-type not in type system - no suitable layer definition found for type [de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl.findLayer(AnnotationSchemaServiceImpl.java:432) ~[webanno-api-dao-4.0.0-beta-5.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl$$FastClassBySpringCGLIB$$c4446552.invoke(<generated>) ~[webanno-api-dao-4.0.0-beta-5.jar!/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750) ~[spring-aop-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295) ~[spring-tx-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationSchemaServiceImpl$$EnhancerBySpringCGLIB$$cade45d7.findLayer(<generated>) ~[webanno-api-dao-4.0.0-beta-5.jar!/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor755.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:521) ~[wicket-ioc-8.6.1.jar!/:8.6.1]
	at com.sun.proxy.$Proxy180.findLayer(Unknown Source) ~[?:?]
	at de.tudarmstadt.ukp.clarin.webanno.ui.project.layers.ProjectLayersPanel$LayerSelectionForm$2.load(ProjectLayersPanel.java:188) ~[webanno-ui-project-4.0.0-beta-5.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.ui.project.layers.ProjectLayersPanel$LayerSelectionForm$2.load(ProjectLayersPanel.java:176) ~[webanno-ui-project-4.0.0-beta-5.jar!/:?]
	at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:128) ~[wicket-core-8.6.1.jar!/:8.6.1]
	at org.apache.wicket.Component.getDefaultModelObject(Component.java:1579) ~[wicket-core-8.6.1.jar!/:8.6.1]
	... 111 more
```

</details>

**Please complete the following information:**
 - Version and build ID: 3.6.3

**Additional context**
Can also happen when a project import fails.

**Comment by reckart** [comment]
With #1187 resolved, this problem no longer exists.
