### ISSUE TITLE
Unable to import re-compressed project ZIP

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#1526]
**Describe the bug**
When a project ZIP file is downloaded and then re-compressed, it contains additional entries which make the import fail. This can be e.g. entries for hidden files created by the OS or it can e.g. be entries for directories which are typically not created on export.

**To Reproduce**
1. Export a project ZIP
2. Extract the ZIP
3. Compress the extracted folder again (but make sure not to include the folder as a root-subfolder in the ZIP)
4. Try importing

**Expected behavior**
Importers should just ignore unrelated entries in the ZIP file including OS metadata and folders.

**Screenshots**

Example of an import failure due to folder entries in the ZIP directory

```
    testing: annotation_ser/5I1JPCZ_3_6.txt/   OK
    testing: annotation_ser/5I1JPCZ_3_6.txt/john.user.ser   OK
```

<details>

```
Caused by: java.lang.IllegalArgumentException: User must be specified
	at org.apache.commons.lang3.Validate.notBlank(Validate.java:454) ~[commons-lang3-3.9.jar:3.9]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.CasStorageServiceImpl.getCasFile(CasStorageServiceImpl.java:591) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl.getCasFile(DocumentServiceImpl.java:276) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl$$FastClassBySpringCGLIB$$7e8e7e07.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685) ~[spring-aop-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.DocumentServiceImpl$$EnhancerBySpringCGLIB$$4e7ae7f7.getCasFile(<generated>) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.AnnotationDocumentExporter.importAnnotationDocumentContents(AnnotationDocumentExporter.java:334) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.exporters.AnnotationDocumentExporter.importData(AnnotationDocumentExporter.java:267) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.export.ProjectExportServiceImpl.importProject(ProjectExportServiceImpl.java:250) ~[classes/:?]
	... 118 more
```

</details>

**Please complete the following information:**
 - Version and build ID: 3.6.3

**Comment by reckart** [comment]
This seems to be a duplicate of https://github.com/webanno/webanno/issues/1641 which has already been resolved - closing this as well.
