### ISSUE TITLE
Exception in monitoring page when document was never opened for annotation

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#159]
Apparently, there is a problem when trying to use the monitoring page on a document that has never been opened for annotation:

```
Caused by: javax.persistence.NoResultException: No entity found for query
        at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:291)
        at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.getAnnotationDocument(RepositoryServiceDbData.java:723)
        at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
        at com.sun.proxy.$Proxy41.getAnnotationDocument(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:435)
        at com.sun.proxy.$Proxy48.getAnnotationDocument(Unknown Source)
        at de.tudarmstadt.ukp.clarin.webanno.monitoring.page.MonitoringPage.updateAgreementTable(MonitoringPage.java:754)
        at de.tudarmstadt.ukp.clarin.webanno.monitoring.page.MonitoringPage.access$1900(MonitoringPage.java:123)
        at de.tudarmstadt.ukp.clarin.webanno.monitoring.page.MonitoringPage$AnnotationTypeSelectionForm$2.onUpdate(MonitoringPage.java:543)
        at org.apache.wicket.ajax.form.AjaxFormComponentUpdatingBehavior.onEvent(AjaxFormComponentUpdatingBehavior.java:153)
        at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:146)
        at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:633)
        ... 71 more
```

When the monitoring page tries to retrieve the annotation document entries from the DB, it should gradefully handle cases where those do not exist.

`de.tudarmstadt.ukp.clarin.webanno.monitoring.page.MonitoringPage.updateAgreementTable(AjaxRequestTarget)` line 749ff (4eb3114b375d038ca3b0860cc1fb473ef203b472)

```
for (SourceDocument document : sourceDocuments) {
  AnnotationDocument annotationDocument = repository.getAnnotationDocument(
    document, user);
  if (annotationDocument.getState().equals(AnnotationDocumentState.FINISHED)) {
    finishedDocuments.add(document);
  }
}
```

WebAnno -- 2.3.0 (2015-07-26 23:34:28, build 4eb3114b375d038ca3b0860cc1fb473ef203b472)

**Comment by reckart** [comment]
Cannot reproduce anymore and the code above doesn't exist anymore in this form. Looks like this is fixed now.
