### ISSUE TITLE
Documents with old ctsv3 file format fail to open

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#206]
Documents from old projects which had file format ctsv3 in source_document database, fail to open in current webanno build. 

It ends up displaying 
`"This is an invalid file. The reader for the document Sentences01 (1).tsv can't read this ctsv3 file type"` 
however the stack trace (you've to force stack trace around RepositoryServiceDbData.java:890 ) to get this, speaks some different story. Seems like some escape characters messing up.

```
2016-03-16 21:20:31  INFO [http-bio-8080-exec-10] [admin] (WebannoCustomTsv3Reader) - Scanning [file:/home/aakash/work/workspaces/ukp/webanno/repository/project/3/document/17/source/]
2016-03-16 21:20:31  INFO [http-bio-8080-exec-10] [admin] (WebannoCustomTsv3Reader) - Found [1] resources to be read
java.lang.NullPointerException
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsv3Reader.getEscapeChars(WebannoCustomTsv3Reader.java:395)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsv3Reader.addAnnotations(WebannoCustomTsv3Reader.java:365)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsv3Reader.setAnnotations(WebannoCustomTsv3Reader.java:172)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsv3Reader.convertToCas(WebannoCustomTsv3Reader.java:122)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoCustomTsv3Reader.getNext(WebannoCustomTsv3Reader.java:604)
	at de.tudarmstadt.ukp.dkpro.core.api.io.JCasResourceCollectionReader_ImplBase.getNext(JCasResourceCollectionReader_ImplBase.java:36)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.convertSourceDocumentToCas(RepositoryServiceDbData.java:2130)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.readAnnotationCas(RepositoryServiceDbData.java:836)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.readAnnotationCas(RepositoryServiceDbData.java:2075)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy47.readAnnotationCas(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:480)
	at com.sun.proxy.$Proxy59.readAnnotationCas(Unknown Source)
	at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.component.AnnotationDetailEditorPanel.getCas(AnnotationDetailEditorPanel.java:894)
	at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.component.AnnotationDetailEditorPanel.reloadLayer(AnnotationDetailEditorPanel.java:2443)
	at de.tudarmstadt.ukp.clarin.webanno.webapp.page.annotation.AnnotationPage$4$2.onClose(AnnotationPage.java:292)
	at org.apache.wicket.extensions.ajax.markup.html.modal.ModalWindow$WindowClosedBehavior.respond(ModalWindow.java:965)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:641)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
	at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:241)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:250)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:236)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:890)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:282)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:178)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at de.tudarmstadt.ukp.clarin.webanno.webapp.WebAnnoLoggingFilter.doFilter(WebAnnoLoggingFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:157)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
```

**Comment by reckart** [comment]
From the file name I guess the file doesn't contain any sensitive information. Maybe you can attach it here or copy/paste the likely problematic part?

@seyyaw

**Comment by seyyaw** [comment]
I am working on using backslash (**\**) in stead of **` ** to escape special characters in an annotation. I will look into it if it actually related to the escaping process.

**Comment by seyyaw** [comment]
In which project is this file of experimental? better you attach the file here.

**Comment by seyyaw** [comment]
Ok, two things.
If you import the project with the **tsv3** file type (the previous deployment before we correct it to **ctsv3**..), it might not work as the TSVwriter/reader is modified, for example header is split into multiple lines and character escaping included. Hence, that file is corrupted.

Otherwise, there was a bug (null pointer exception for empty annotations) which is now fixed. update your local installation, remove the entry from annotation document (if exist) and try to re-open. It should work
