### ISSUE TITLE
Webanno crashes if you try to open second document while AnnotationDetailEditorPanel is selected/opened

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#210]
**Steps to reproduce**

1. Open any document in any project.
2. I observed this with SemPred (I'm sure it happens with other layers as well which open AnnotationDetailEditorPanel). Select layer to SemPred and double click on text to create annotation. 
3. Without clearing/un-selecting the annotation, leave the AnnotationDetailEditorPanel open like this ![unclearedannotation](https://cloud.githubusercontent.com/assets/1897100/13927832/9dd62d94-ef93-11e5-87ee-ffa47fd1608e.png)

4. Click on "Open" and try to open another document which has some existing annotations in it. 

**Expected**
The other document should opens normally.

**What happens**
Webanno crashes with internal error.

```
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (AnnotationPage) - BEGIN LOAD_DOCUMENT_ACTION
2016-03-21 18:38:15 DEBUG [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Getting annotation document [2221008_unicum_03-03-2003.xml.xmi] with ID [33] in project ID [5] for user [admin]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Upgraded CAS of user [admin] for document [2221008_unicum_03-03-2003.xml.xmi]  in project ID [5]
2016-03-21 18:38:15 DEBUG [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Updating annotation document [2221008_unicum_03-03-2003.xml.xmi] with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Updated annotation document [2221008_unicum_03-03-2003.xml.xmi] with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Removed surplus history file [admin.ser.1458579958000.bak] for document with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Removed outdated history file [admin.ser.1458579960000.bak]  for document with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Removed outdated history file [admin.ser.1458579962000.bak]  for document with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Removed outdated history file [admin.ser.1458580024000.bak]  for document with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Removed outdated history file [admin.ser.1458580029000.bak]  for document with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Removed outdated history file [admin.ser.1458580064000.bak]  for document with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Removed outdated history file [admin.ser.1458580141000.bak]  for document with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Removed outdated history file [admin.ser.1458580145000.bak]  for document with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Removed outdated history file [admin.ser.1458580152000.bak]  for document with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Removed outdated history file [admin.ser.1458580174000.bak]  for document with ID [33] in project ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Read constraints set file [1.txt] for project [kp3_exp_20150825] with ID [5]
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (BratAnnotator) - BEGIN bratRenderCommand
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (BratAnnotator) - END bratRenderCommand
2016-03-21 18:38:15  INFO [http-bio-8080-exec-8] [admin] (AnnotationPage) - END LOAD_DOCUMENT_ACTION
2016-03-21 18:38:15 DEBUG [http-bio-8080-exec-8] [admin] (RepositoryServiceDbData) - Getting annotation document [2221008_unicum_03-03-2003.xml.xmi] with ID [33] in project ID [5] for user [admin]
2016-03-21 18:38:15 ERROR [http-bio-8080-exec-8] [admin] (DefaultExceptionMapper) - Unexpected error occurred
org.apache.wicket.WicketRuntimeException: Method onRequest of interface org.apache.wicket.behavior.IBehaviorListener targeted at org.apache.wicket.extensions.ajax.markup.html.modal.ModalWindow$WindowClosedBehavior@2c777fc0 on component [ModalWindow [Component id = openDocumentsModal]] threw an exception
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:268)
	at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:241)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:250)
	at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:236)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:890)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:282)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:178)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at de.tudarmstadt.ukp.clarin.webanno.webapp.WebAnnoLoggingFilter.doFilter(WebAnnoLoggingFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:157)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
	... 74 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Workaround**
If you click on "Clear" button in AnnotationDetailEditorPanel and then try to open second document, it'll open normally. However, I suspect that users are going to encounter this error because of not clearing it.

**Comment by seyyaw** [comment]
clear selection on **open document** actions

**Comment by reckart** [comment]
Good catch! I think I also recently stumbled over that and then didn't know how to reproduce it  @:)
