### ISSUE TITLE
CasDoctor should check that all annotations start/end in sentences

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#217]
WebAnno cannot deal with annotations that do not start/end at or within sentence boundaries. Also the brat visualization has no concept of such annotations. They can cause exceptions like

```
Caused by: java.lang.NullPointerException
      at de.tudarmstadt.ukp.clarin.webanno.brat.controller.SpanAdapter.render(SpanAdapter.java:203)
      at de.tudarmstadt.ukp.clarin.webanno.brat.controller.BratAjaxCasController.render(BratAjaxCasController.java:281)
      at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.BratAnnotator.bratRenderCommand(BratAnnotator.java:520)
      at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.BratAnnotator.bratRender(BratAnnotator.java:592)
      at de.tudarmstadt.ukp.clarin.webanno.webapp.page.annotation.AnnotationPage.loadDocumentAction(AnnotationPage.java:816)
      at de.tudarmstadt.ukp.clarin.webanno.webapp.page.annotation.AnnotationPage.access$200(AnnotationPage.java:81)
      at de.tudarmstadt.ukp.clarin.webanno.webapp.page.annotation.AnnotationPage$3$2.onClose(AnnotationPage.java:224)
      at org.apache.wicket.extensions.ajax.markup.html.modal.ModalWindow$WindowClosedBehavior.respond(ModalWindow.java:965)
      at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:633)
```

CasDoctor should check if there are any annotations start do not start/end at or within sentence boundaries and reject such files. I don't see a sensible repair function here.

**Comment by mmeva** [comment]
Does it mean that a span annotation starting in one sentence and ending in an other would be not possible? -- We do have many annotations spanning over sentences.

**Comment by reckart** [comment]
@mmeva as long begin and end do not have to be in the *same* sentence. They just cannot be *between* sentences.

**Comment by mmeva** [comment]
I am sorry, but how can an annotation be made between sentences?
Or do you mean zero-length annotation?
Or probably incorrectly created preannotations with wrong annotation boundaries?

**Comment by reckart** [comment]
@mmeva The thing is: in WebAnno you cannot make an annotation between sentences. But if you create an XMI file manually, then that file my contain such annotations and WebAnno does not like that.

E.g. if an XMI file has something like

```
10 - 20  sentence 1
22 - 23  POS
30 - 40  sentence 2
```

Then WebAnno will throw above exception when it tries rendering POS to the screen.

This is only a problem for imported XMI or CAS files.

**Comment by mmeva** [comment]
(Ok, this ist the second case I mentioned.)
Thank you for the explanation.
