### ISSUE TITLE
Curation: Annotation text shrinked to a tiny size

### ISSUE THREAD

**Issue by mmeva** [webanno/webanno#248]
In Curation, the Annotation text is shrinking to a tiny size after some activity - e.g. if the curator delete an annotated instance (but the behaviour is not deterministic).

Example in the attached picture 
![curation_annotationtexttiny](https://cloud.githubusercontent.com/assets/2294086/14604244/daaef6ac-0572-11e6-8185-7fada9545d73.png)

(Project, file and WebAnno version see attachment.)

**Comment by mmeva** [comment]
The same happens also if the curator just chooses one of the users' annotation as a correct one for copying into the Annotation panel.

**Comment by mmeva** [comment]
Alternativ: No text at all is shown, see attached picture
![curation_annotationtextmissing](https://cloud.githubusercontent.com/assets/2294086/14610464/56cd7b76-058e-11e6-9253-71748cd37c98.png)

**Comment by reckart** [comment]
I expect some JavaScript error to be occurring. Can you check in the JavaScript console / web developer tools of your browser if you see any error message? Please try opening the console before triggering the problem. If you try opening the console after the problem has been triggered, it will likely cause a window resize which triggers a page reload.

**Comment by TFeige** [comment]
During our tests, this occurs quite frequently. It is not restricted to Curation, but occurs in Annotation mode as well. This is the output: 
```
Timeout in loading fonts visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:3471:1
Visualizer/<() visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:3471

Rendering terminated due to: IndexSizeError: Index or size is negative or greater than the allowed amount Visualizer/getTextAndSpanTextMeasurements/textSizes<@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1210:10
Visualizer/getTextMeasurements/</<@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1149:1
.each@http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:2880
Visualizer/getTextMeasurements/<@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1148:1
.each@http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:2880
n.prototype.each@http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:845
Visualizer/getTextMeasurements@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1144:1
Visualizer/getTextAndSpanTextMeasurements@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1172:17
Visualizer/renderDataReal@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1451:13
Visualizer/renderData/<@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:3085:1
```
Version: beta 5 and WebAnno -- 3.0.0-SNAPSHOT (2016-06-20 00:09:09, build 6867d90b45ada56398a6f1186008086e811f9e06)

**Comment by reckart** [comment]
Hm. I have never seen that. It may be a problem with very large annotation spans? Or there is a problem with some odd characters.

Does the problem also occur if you open the file in LTR mode?

Would be great if you could privately send me a project that triggers this problem.

**Comment by TFeige** [comment]
The problem occurs in LTR mode as well. Usually with larger annotation spans, e.g. covering one sentence. I'll send you the project immediately.

**Comment by TFeige** [comment]
It occurs while annotating الشارع ‏صادق, but only with Firefox.

Then I switched to Chromium and opened Farhud.xmi with page and section layers activated. The bug occured. This time with different error messages: 
```
visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:3090 Rendering terminated due to: IndexSizeError: Failed to execute 'getEndPositionOfChar' on 'SVGTextContentElement': The charnum provided (319) is greater than or equal to the maximum bound (319). Error: Failed to execute 'getEndPositionOfChar' on 'SVGTextContentElement': The charnum provided (319) is greater than or equal to the maximum bound (319).
    at Error (native)
    at http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…sourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1210:15
    at .<anonymous> (http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…esourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1149:1)
    at Function.n.extend.each (http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.D…ference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:2882)
    at SVGTextElement.<anonymous> (http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…esourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1148:3)
    at Function.n.extend.each (http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.D…ference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:2882)
    at n.fn.n.each (http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.D…eference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:847)
    at getTextMeasurements (http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…sourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1144:34)
    at getTextAndSpanTextMeasurements (http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…sourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1172:17)
    at renderDataReal (http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…sourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1451:13)
```

**Comment by reckart** [comment]
Looks like there is a RTL marker (UTF-8 `E2 80 8F`) in the string `الشارع ‏صادق` which causes the problem.

**Comment by reckart** [comment]
Can anbody confirm whether this issue actually still exists?

**Comment by TFeige** [comment]
It seems that this issue is resolved with beta 6.

**Comment by reckart** [comment]
I'll close this then. If somebody re-encounters the problem, please let us know.
