### ISSUE TITLE
Avoid NPE when a constraint references a non-existing feature

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#254]
Avoid NPE when a constraint references a non-existing feature

```
Caused by: java.lang.NullPointerException
	at org.apache.uima.cas.impl.FeatureStructureImpl.getFeatureValue(FeatureStructureImpl.java:228)
	at de.tudarmstadt.ukp.clarin.webanno.constraints.evaluator.ValuesGenerator.getValue(ValuesGenerator.java:176)
	at de.tudarmstadt.ukp.clarin.webanno.constraints.evaluator.ValuesGenerator.conditionMatches(ValuesGenerator.java:115)
	at de.tudarmstadt.ukp.clarin.webanno.constraints.evaluator.ValuesGenerator.ruleTriggers(ValuesGenerator.java:105)
	at de.tudarmstadt.ukp.clarin.webanno.constraints.evaluator.ValuesGenerator.generatePossibleValues(ValuesGenerator.java:85)
	at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.component.AnnotationDetailEditorPanel$TextFeatureEditor.populateTagsBasedOnRules(AnnotationDetailEditorPanel.java:1583)
	at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.component.AnnotationDetailEditorPanel$TextFeatureEditor.<init>(AnnotationDetailEditorPanel.java:1493)
	at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.component.AnnotationDetailEditorPanel$FeatureEditorPanelContent.populateItem(AnnotationDetailEditorPanel.java:1208)
	at org.apache.wicket.markup.repeater.RefreshingView$1.newItem(RefreshingView.java:114)
	at org.apache.wicket.markup.repeater.DefaultItemReuseStrategy$1.next(DefaultItemReuseStrategy.java:75)
	at org.apache.wicket.markup.repeater.DefaultItemReuseStrategy$1.next(DefaultItemReuseStrategy.java:56)
	at org.apache.wicket.markup.repeater.RefreshingView.addItems(RefreshingView.java:189)
	at org.apache.wicket.markup.repeater.RefreshingView.onPopulate(RefreshingView.java:97)
	at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:123)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1684)
``

**Comment by aakashysharma** [comment]
@reckart Isn't it fixed?

**Comment by reckart** [comment]
I think it is and I forgot to close it.
