### ISSUE TITLE
Rendering error with zero-width characters in RTL mode

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#307]
During our tests, this occurs quite frequently. It is not restricted to Curation, but occurs in Annotation mode as well. This is the output: 
```
Timeout in loading fonts visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:3471:1
Visualizer/<() visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:3471

Rendering terminated due to: IndexSizeError: Index or size is negative or greater than the allowed amount Visualizer/getTextAndSpanTextMeasurements/textSizes<@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1210:10
Visualizer/getTextMeasurements/</<@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1149:1
.each@http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:2880
Visualizer/getTextMeasurements/<@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1148:1
.each@http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:2880
n.prototype.each@http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.DynamicJQueryResourceReference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:845
Visualizer/getTextMeasurements@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1144:1
Visualizer/getTextAndSpanTextMeasurements@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1172:17
Visualizer/renderDataReal@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1451:13
Visualizer/renderData/<@http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.webanno.brat.resource.BratVisualizerResourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:3085:1
```
Version: beta 5 and WebAnno -- 3.0.0-SNAPSHOT (2016-06-20 00:09:09, build 6867d90b45ada56398a6f1186008086e811f9e06)

Edit: The catalina log file contains a warning regarding the annotation, that led to the bug:
```
2016-06-29 13:48:11  INFO [http-bio-18080-exec-9] [admin] (BratAnnotator) - BEGIN bratRenderCommand
2016-06-29 13:48:11  INFO [http-bio-18080-exec-9] [admin] (BratAnnotator) - END bratRenderCommand
2016-06-29 13:48:11  INFO [http-bio-18080-exec-9] [admin] (BratAnnotator) - AJAX-RPC DONE: [spanOpenDialog]
2016-06-29 13:48:11  WARN [http-bio-18080-exec-9] [admin] (BratAnnotator) - AJAX-RPC: Action [spanOpenDialog] produced no result!
2016-06-29 13:48:11  INFO [http-bio-18080-exec-9] [admin] (ApplicationPageBase) - admin: The [semantic_layer] annotation has been created/updated. Label: [(semantic_layer)]
```

Original: https://github.com/webanno/webanno/issues/248#issuecomment-229332888

**Comment by reckart** [comment]
Hm. I have never seen that. It may be a problem with very large annotation spans? Or there is a problem with some odd characters.

Does the problem also occur if you open the file in LTR mode?

Would be great if you could privately send me a project that triggers this problem.

**Comment by reckart** [comment]
@TFeige: The problem occurs in LTR mode as well. Usually with larger annotation spans, e.g. covering one sentence. I'll send you the project immediately.

**Comment by reckart** [comment]
@TFeige: It occurs while annotating الشارع ‏صادق, but only with Firefox.

Then I switched to Chromium and opened Farhud.xmi with page and section layers activated. The bug occured. This time with different error messages: 
```
visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:3090 Rendering terminated due to: IndexSizeError: Failed to execute 'getEndPositionOfChar' on 'SVGTextContentElement': The charnum provided (319) is greater than or equal to the maximum bound (319). Error: Failed to execute 'getEndPositionOfChar' on 'SVGTextContentElement': The charnum provided (319) is greater than or equal to the maximum bound (319).
    at Error (native)
    at http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…sourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1210:15
    at .<anonymous> (http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…esourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1149:1)
    at Function.n.extend.each (http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.D…ference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:2882)
    at SVGTextElement.<anonymous> (http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…esourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1148:3)
    at Function.n.extend.each (http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.D…ference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:2882)
    at n.fn.n.each (http://localhost:18080/webanno/wicket/resource/org.apache.wicket.resource.D…eference/jquery/jquery-2.1.4-ver-37377040C98D18191D96A90A411ED1E9.js:2:847)
    at getTextMeasurements (http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…sourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1144:34)
    at getTextAndSpanTextMeasurements (http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…sourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1172:17)
    at renderDataReal (http://localhost:18080/webanno/wicket/resource/de.tudarmstadt.ukp.clarin.we…sourceReference/visualizer-ver-9762BA4687BA82D800463FEB6C942DA7.js:1451:13)
```

**Comment by reckart** [comment]
@TFeige: I hope this should be fixed now, but there might be edge cases. E.g. when annotating a span that begins/ends with a RTL/LTR marker. I would recommend cleaning the texts of zero-width characters before importing them into WebAnno. Please reopen if you experience further issues with texts containing RTL/LTR markers.
