### ISSUE TITLE
Sometimes an NPE when opening another document

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#346]
Sometimes an NPE when opening another document:

```
java.lang.NullPointerException
     at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.component.AnnotationDetailEditorPanel.setLayerAndFeatureModels(AnnotationDetailEditorPanel.java:1016)
     at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.component.AnnotationDetailEditorPanel.reloadLayer(AnnotationDetailEditorPanel.java:2547)
     at de.tudarmstadt.ukp.clarin.webanno.webapp.page.annotation.AnnotationPage$6$2.onClose(AnnotationPage.java:321)
     at org.apache.wicket.extensions.ajax.markup.html.modal.ModalWindow$WindowClosedBehavior.respond(ModalWindow.java:965)
     at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:641)
     at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by reckart** [comment]
Seems to be caused by the selection not being cleared when switching to another document.

**Comment by reckart** [comment]
Actually looks more related to remember layer being active and a bug and a missing null check...

**Comment by reckart** [comment]
With the present "fix", no creation of relation annotations is possible anymore...
