### ISSUE TITLE
Error importing TSV file

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#358]
Importing the attached TSV file into the attached model fails with a NPE.

```
Caused by: java.lang.NullPointerException
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3Reader.addAnnotations(WebannoTsv3Reader.java:423)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3Reader.setAnnotations(WebannoTsv3Reader.java:202)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3Reader.convertToCas(WebannoTsv3Reader.java:124)
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3Reader.getNext(WebannoTsv3Reader.java:758)
	at de.tudarmstadt.ukp.dkpro.core.api.io.JCasResourceCollectionReader_ImplBase.getNext(JCasResourceCollectionReader_ImplBase.java:36)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.convertSourceDocumentToCas(RepositoryServiceDbData.java:2133)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.uploadSourceDocument(RepositoryServiceDbData.java:1510)
```

I had a quick try at debugging this, but I am not very familiar with the TSV code. It seems there is a "annosPerRef" map which should contain references to all annotations (?). But it looks like the target (`1-30[8_0]`) of line this line is not present in `annosPerRef.get(depType)`.

```
1-1	0-7	Respect	abstract	new	coref	1-30[8_0]
```

Full TSV file (also attached)

```
#FORMAT=WebAnno TSV 3
#T_SP=webanno.custom.Referent|entity|infstat
#T_RL=webanno.custom.Coref|type|BT_webanno.custom.Referent


#Text=Respect Thais are a polite people and , while remarkably tolerant of foreigners gallivanting on their beaches and with their women , you ll find that you will get more respect if you in turn treat them and their customs with respect .
1-1	0-7	Respect	abstract	new	coref	1-30[8_0]	
1-2	8-13	Thais	person	new	ana	1-37	
1-3	14-17	are	_	_	_	_	
1-4	18-19	a	_	_	_	_	
1-5	20-26	polite	_	_	_	_	
1-6	27-33	people	_	_	_	_	
1-7	34-37	and	_	_	_	_	
1-8	38-39	,	_	_	_	_	
1-9	40-45	while	_	_	_	_	
1-10	46-56	remarkably	_	_	_	_	
1-11	57-65	tolerant	_	_	_	_	
1-12	66-68	of	_	_	_	_	
1-13	69-79	foreigners	person	new	coref	9-31	
1-14	80-92	gallivanting	_	_	_	_	
1-15	93-95	on	_	_	_	_	
1-16	96-101	their	place[4]	new[4]	_	_	
1-17	102-109	beaches	place[4]	new[4]	_	_	
1-18	110-113	and	_	_	_	_	
1-19	114-118	with	_	_	_	_	
1-20	119-124	their	person[5]	new[5]	_	_	
1-21	125-130	women	person[5]	new[5]	_	_	
1-22	131-132	,	_	_	_	_	
1-23	133-136	you	person	acc	ana	1-27	
1-24	137-139	ll	_	_	_	_	
1-25	140-144	find	_	_	_	_	
1-26	145-149	that	_	_	_	_	
1-27	150-153	you	person	acc	ana	1-33	
1-28	154-158	will	_	_	_	_	
1-29	159-162	get	_	_	_	_	
1-30	163-167	more	abstract[8]	giv[8]	coref	1-42[0_8]	
1-31	168-175	respect	abstract[8]	giv[8]	_	_	
1-32	176-178	if	_	_	_	_	
1-33	179-182	you	person	acc	ana	2-22[19_0]	
1-34	183-185	in	_	_	_	_	
1-35	186-190	turn	_	_	_	_	
1-36	191-196	treat	_	_	_	_	
1-37	197-201	them	person	giv	coref|bridge	3-2|1-39[11_0]	
1-38	202-205	and	_	_	_	_	
1-39	206-211	their	object[11]	acc[11]	_	_	
1-40	212-219	customs	object[11]	acc[11]	_	_	
1-41	220-224	with	_	_	_	_	
1-42	225-232	respect	abstract	giv	_	_	
1-43	233-234	.	_	_	_	_	
```

[Issue_358_2016-10-01_2016.zip](https://github.com/webanno/webanno/files/504562/Issue_358_2016-10-01_2016.zip)

[Issue_358.tsv.zip](https://github.com/webanno/webanno/files/504563/Issue_358.tsv.zip)

**Comment by seyyaw** [comment]
@reckart Can you send  the annotation file (binary) by email?

**Comment by seyyaw** [comment]
I try to annotate the arc annotations myself.
Error: `Layer do not support arc annotation`. Do you fix this issue @reckart ?

**Comment by reckart** [comment]
It should be fixed, but I'll double check that...

**Comment by reckart** [comment]
Ok, the "Layer do not support arc annotation" should now really be fixed... _fingers crossed_

@seyyaw do you see any problem with the TSV file itself? Is it inconsistent/broken in any way?

@amir-zeldes can you send us a binary export of the *GUM_voyage_thailand_copy.tsv* file? If you don't have Seid's mail, you can also send it to me and I forward it.

**Comment by seyyaw** [comment]
@reckart I want to check if the problem occurs only during import or it was due to export process. For example, the following line refers a `dependent` at sentence 9 but the TSV file has only one sentence
```1-13	69-79	foreigners	person	new	coref	9-31```

**Comment by amir-zeldes** [comment]
Sure, here are the files. The file has 38 sentences according to my TSV file, not sure why you're only seeing one. See attached - thanks for working on this!

BTW this is still from build d0df25d9bd692e98a40871bf7b850d5c8077c1c1, I need to upgrade.
[thailand.zip](https://github.com/webanno/webanno/files/505489/thailand.zip)

**Comment by reckart** [comment]
@seyyaw that was my mistake. I stripped the file down to a single sentence because that was where the exception occurred. The exception also occurred before I had stripped it down. I hadn't noticed that the first sentence referred to sentences later.

**Comment by seyyaw** [comment]
Thanks @amir-zeldes .
This is a nice bug report. There were logical error on multi-feature-multi-tokne annotations importing. It should work now!

**Comment by amir-zeldes** [comment]
Thanks for fixing, but I can't seem to run this build (I've tried 1476 and the subsequent 1477). I'm getting this trace:

```
HTTP Status 500 -

type Exception report

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Filter execution threw an exception
	org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:178)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:164)
	de.tudarmstadt.ukp.clarin.webanno.webapp.WebAnnoLoggingFilter.doFilter(WebAnnoLoggingFilter.java:52)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:149)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
root cause

java.lang.NoSuchMethodError: javax.servlet.http.HttpServletRequest.isAsyncStarted()Z
	org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:234)
	org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
	org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:178)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:164)
	de.tudarmstadt.ukp.clarin.webanno.webapp.WebAnnoLoggingFilter.doFilter(WebAnnoLoggingFilter.java:52)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:149)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
	org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
	org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
	org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
note The full stack trace of the root cause is available in the Apache Tomcat/6.0.24 logs.

Apache Tomcat/6.0.24
```

**Comment by amir-zeldes** [comment]
@seyyaw @reckart  - let me know if you need other log files as well. Thanks!

**Comment by reckart** [comment]
Tomcat 6 is no longer supported. You need at least Tomcat 7.

**Comment by reckart** [comment]
Better Tomcat 8 (if you are upgrading anyway and Tomcat 8 is available).

**Comment by reckart** [comment]
Switched back to Wicket 6.24.0 for the moment to support Tomcat 6... cf.
* https://github.com/webanno/webanno/issues/360 - Upgrading dependencies
* https://github.com/webanno/webanno/issues/365 - Alternative to Winstone-based standalone JAR
