### ISSUE TITLE
Documents appearing more than once in document picker in curation mode

### ISSUE THREAD

**Issue by neumannm** [webanno/webanno#410]
I think I found a small bug in WebAnno 3.0.0-SNAPSHOT as of 23-11-2016.

When going in curation mode, the "Open document" dialog opens. In the list of documents, documents that have been finished by more than one annotator also appear more than once. I can only assume that they appear as often as there are annotators that finished it, but I'm not sure because I only have two.

Here's a screenshot.
![webannobug](https://cloud.githubusercontent.com/assets/729045/21224316/e4699bfe-c2cb-11e6-80cd-f0f79f8d6a40.png)

So there are three documents appearing twice. The 20089.xmi is the one I curated and clicked on "done" (I just randomly opened one of them from the list for curation).

**Comment by reckart** [comment]
Sounds like a bug, yes. I recently updated that code to make it faster - looks like that might be causing this new problem.

**Comment by GiantEnemyCrab** [comment]
I can confirm that this is happening in my environment, too, for curation document opening. I am seeing the same file name twice. I tend to use the latest commit from upstream.

**Comment by GiantEnemyCrab** [comment]
While I tried to integrate all the changes for 3.0.1, I noticed that trying to open Curation results in Internal Error the following contents in catalina.out:

```
Caused by: java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'webanno.sourcedocu2_.name' which is not in SELECT list; thisis incompatible with DISTINCT
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2625)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2119)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2281)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:93)
        at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)
        ... 137 more
```

By reverting the specific code to a previous version, at least I am able to open Curation document selection view.
