### ISSUE TITLE
Project export fails on WebAnno 2.3.1

### ISSUE THREAD

**Issue by coltekin** [webanno/webanno#445]
When we try to export any project from the projects menu 'Export' tab,
the user interface is stuck at 0%.  Meanwhile, we see the exception
thrown in the tomcat logs (included below).

Our aim for exporting projects is to upgrade to WebAnno 3.  So, for
our purposes, if there is a workaround that would allow upgrading from
version 2.3.1 to version 3 safely without exporting projects through
web interface (for example some command-line tool/method to export the
projects), it would solve our problem.

Below are some details that may be useful:

We run WebAnno 2.3.1 release on Ubuntu 16.04.2 LTS with oracle-java8
and tomcat7 from the distribution (7.0.68).

Exact WebAnno version string is
```
WebAnno -- 2.3.1 (2016-04-07 10:40:53, build 6c4cc8b8483131e47e2b7f2b9fbe94b8c1b720df)
```

The exception fromt the server logs:

```
javax.persistence.EntityNotFoundException: Unable to find de.tudarmstadt.ukp.clarin.webanno.model.TagSet with id 124
	at org.hibernate.ejb.Ejb3Configuration$Ejb3EntityNotFoundDelegate.handleEntityNotFound(Ejb3Configuration.java:155)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:210)
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:251)
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:148)
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1079)
	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1006)
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:613)
	at org.hibernate.type.EntityType.resolve(EntityType.java:441)
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:168)
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:134)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:995)
	at org.hibernate.loader.Loader.doQuery(Loader.java:874)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:259)
	at org.hibernate.loader.Loader.loadEntity(Loader.java:2033)
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82)
	at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72)
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3719)
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:449)
	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:418)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:204)
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:251)
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:148)
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1079)
	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1006)
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:613)
	at org.hibernate.type.EntityType.resolve(EntityType.java:441)
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:168)
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:134)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:995)
	at org.hibernate.loader.Loader.doQuery(Loader.java:874)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
	at org.hibernate.loader.Loader.doList(Loader.java:2438)
	at org.hibernate.loader.Loader.doList(Loader.java:2424)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2254)
	at org.hibernate.loader.Loader.list(Loader.java:2249)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:470)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1248)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
	at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:310)
	at com.sun.proxy.$Proxy92.getResultList(Unknown Source)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.listMiraTemplates(RepositoryServiceDbData.java:2183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:196)
	at com.sun.proxy.$Proxy41.listMiraTemplates(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:435)
	at com.sun.proxy.$Proxy48.listMiraTemplates(Unknown Source)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel$FileGenerator.exportProjectSettings(ProjectExportPanel.java:655)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel$FileGenerator.generateZipFile(ProjectExportPanel.java:483)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectExportPanel$FileGenerator.run(ProjectExportPanel.java:447)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by reckart** [comment]
You have probably hit https://github.com/webanno/webanno/issues/86. So somebody created a tagset, assigned it to a layer, and then deleted the tagset afterwards. 

You could try working around this by logging into the MySQL DB, searching in the "annotation_feature" table for features using tagset 124 and setting the tagset to null there.

**Comment by coltekin** [comment]
This was indeed the problem. The workaround worked.
Thanks!
