### ISSUE TITLE
Make DescriptionTooltipBehavior more reusable

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#52]
I would like to use the DescriptionTooltipBehavior also in the AgreementTable, so it needs to go to a separate class.

While at it, also style it a bit better to be in line with the rest of the app. Maybe even add line-breaking and markdown support in the process if it's easy.

**Comment by reckart** [comment]
Works when built with Eclipse, but when built with Maven (e.g. in the standalone), getting this exception

```
org.apache.wicket.markup.MarkupNotFoundException: Failed to find markup file associated. DescriptionTooltipPanel: [DescriptionTooltipPanel [Component id = tooltip]]
	at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.getMarkup(AssociatedMarkupSourcingStrategy.java:97)
	at org.apache.wicket.MarkupContainer.getMarkup(MarkupContainer.java:451)
	at org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:654)
	at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:76)
	at org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2536)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1496)
	at org.apache.wicket.Component.internalRender(Component.java:2366)
	at org.apache.wicket.Component.render(Component.java:2294)
	at org.apache.wicket.core.util.string.ComponentRenderer.renderComponent(ComponentRenderer.java:118)
	at com.googlecode.wicket.jquery.ui.widget.tooltip.CustomTooltipBehavior.render(CustomTooltipBehavior.java:93)
	at com.googlecode.wicket.jquery.ui.widget.tooltip.CustomTooltipBehavior.bind(CustomTooltipBehavior.java:71)
	at org.apache.wicket.Behaviors.add(Behaviors.java:59)
	at org.apache.wicket.Component.add(Component.java:4496)
```

**Comment by mmev** [comment]
On which instance of WebAnno should the markup work (markdown)?
As I see, it is not working at the moment.
(Probably, a new version will be uploaded soon?)
Current versions:
Testing: WebAnno -- 3.0.0-SNAPSHOT (2015-07-31 16:45:33, build 0ad6fdf69560a5cc8dd8dc17c77165a6563c9ab6)
Experimental: WebAnno -- 3.0.0-SNAPSHOT (2015-07-30 15:31:47, build 0ad6fdf69560a5cc8dd8dc17c77165a6563c9ab6)

**Comment by reckart** [comment]
Markdown support is in the code, but it is not actually wired up to anything yet. I guess that @aakashysharma will be looking into this. Does this have a particular priority to you?

**Comment by mmev** [comment]
No, I only would like to have line breaks -- which are now also working on experimental :)

WebAnno -- 3.0.0-SNAPSHOT (2015-08-02 22:22:20, build 340461e53552622290e31f1c050432f39d8f6d68)

Could this behaviour also be uploaded in Testing, too?
