### ISSUE TITLE
Chain layers are broken

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#56]
When opening a document in a project that defines a custom chain layer, an exception is thrown:

```
java.lang.IllegalArgumentException: Unsupported type [webanno.custom.Chain] on feature [referenceType]
     at de.tudarmstadt.ukp.clarin.webanno.brat.annotation.component.AnnotationDetailEditorPanel$FeatureEditorPanelContent.populateItem(AnnotationDetailEditorPanel.java:997)
     at org.apache.wicket.markup.repeater.RefreshingView$1.newItem(RefreshingView.java:114)
     at org.apache.wicket.markup.repeater.DefaultItemReuseStrategy$1.next(DefaultItemReuseStrategy.java:75)
     at org.apache.wicket.markup.repeater.DefaultItemReuseStrategy$1.next(DefaultItemReuseStrategy.java:56)
     at org.apache.wicket.markup.repeater.RefreshingView.addItems(RefreshingView.java:189)
     at org.apache.wicket.markup.repeater.RefreshingView.onPopulate(RefreshingView.java:97)
     at org.apache.wicket.markup.repeater.AbstractRepeater.onBeforeRender(AbstractRepeater.java:123)
     at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
     at org.apache.wicket.Component.beforeRender(Component.java:1017)
```

WebAnno -- 3.0.0-SNAPSHOT (2015-08-02 01:46:47, build d75d8bbb47e3d46773c2b8e1b41363d6cb5d62b7)

**Comment by reckart** [comment]
Actually only happens when the chain layers is the first layer and selected by default when a document is opened.
