### ISSUE TITLE
Add "cancel" button to project settings tab(s)

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#71]
Different tabs under project settings don't have an option to cancel.

**Comment by reckart** [comment]
Why does someDetailForm.setModelObject(null); not work?

**Comment by aakashysharma** [comment]
Unlike ProjectConstraintsPanel, every other panel page is maintaining state for the secondary form which shows various details about project/tagset etc.

If we use someDetailForm.setModelObject(null) Upon clicking Cancel, it works but loading the page again has dependency on the object which we configured null. This causes page to crash.

Following stack trace from ProjectLayersPanel.java when LayerDetailForm.this.setModelObject(null) is used. 

```
2015-08-31 12:05:05 ERROR [http-bio-8080-exec-10] [admin] (DefaultExceptionMapper) - Unexpected error occurred
org.apache.wicket.WicketRuntimeException: Error attaching this container for rendering: [LayerDetailForm [Component id = layerDetailForm]]
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1696)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3833)
	at org.apache.wicket.markup.html.form.Form.onBeforeRender(Form.java:1803)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1684)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3833)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1684)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3833)
	at org.apache.wicket.extensions.markup.html.tabs.TabbedPanel.onBeforeRender(TabbedPanel.java:266)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1684)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3833)
	at org.apache.wicket.markup.html.form.Form.onBeforeRender(Form.java:1803)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1684)
	at org.apache.wicket.Component.onBeforeRender(Component.java:3833)
	at org.apache.wicket.Page.onBeforeRender(Page.java:809)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:949)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.Component.internalPrepareForRender(Component.java:2201)
	at org.apache.wicket.Page.internalPrepareForRender(Page.java:240)
	at org.apache.wicket.Component.render(Component.java:2290)
	at org.apache.wicket.Page.renderPage(Page.java:1024)
	at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:139)
	at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:284)
	at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:890)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:97)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:282)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:147)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at de.tudarmstadt.ukp.clarin.webanno.webapp.WebAnnoLoggingFilter.doFilter(WebAnnoLoggingFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:146)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:183)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectLayersPanel$LayerDetailForm$2.onConfigure(ProjectLayersPanel.java:458)
	at org.apache.wicket.Component.configure(Component.java:1055)
	at org.apache.wicket.Component.internalBeforeRender(Component.java:940)
	at org.apache.wicket.Component.beforeRender(Component.java:1017)
	at org.apache.wicket.MarkupContainer.onBeforeRenderChildren(MarkupContainer.java:1684)
	... 95 more

```

**Comment by reckart** [comment]
It seems that the forms assume that an empty non-database object is set in the detail forms when they are "inactive", e.g. related to your stack trace see:

    public LayerDetailForm(String id)
    {
      super(id, new CompoundPropertyModel<AnnotationLayer>(new EntityModel<AnnotationLayer>(
        new AnnotationLayer())));

The location triggering the exception above builds on this assumption by not checking the model object for being null before trying to get a value from it.

For consistency with the current assumptions, I guess the cancel button should reset the form to use an empty object, e.g. `new AnnotationLayer()`. 

In general proper null checking and not using an empty object would probably be the better approach. For the DetailForm in ProjectConstraintsPanel, I implemented proper null handling and also use it for the cancel button.
