### ISSUE TITLE
TSV3 export fails with zero-length annotations between adjacent tokens

### ISSUE THREAD

**Issue by adrianeboyd** [webanno/webanno#713]
I created this example with a plain text import to try zero-length annotations at the beginning and ends of sentences (not just documents, see #712; the closest I could get was one character before the end of the sentence). I can export (and also re-import) it as binary CAS but the TSV3 export fails.

![zerolengthexample](https://user-images.githubusercontent.com/5794899/32893807-1bee61c8-cadb-11e7-83af-649f0c6b0f82.png)

```
Caused by: java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:854) ~[?:1.8.0_131]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.internal.tsv3x.Tsv3XCasDocumentBuilder.of(Tsv3XCasDocumentBuilder.java:183) ~[webanno-io-tsv-3.4.0-SNAPSHOT.jar!/:?]
	at de.tudarmstadt.ukp.clarin.webanno.tsv.WebannoTsv3XWriter.process(WebannoTsv3XWriter.java:56) ~[webanno-io-tsv-3.4.0-SNAPSHOT.jar!/:?]
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) ~[uimaj-core-2.10.2.jar!/:2.10.2]
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401) ~[uimaj-core-2.10.2.jar!/:2.10.2]
```

The exported binary CAS for reference: 

[text.bin.gz](https://github.com/webanno/webanno/files/1478676/text.bin.gz)

**Comment by reckart** [comment]
Great! That will help me to set up a unit test. Good catch!

**Comment by reckart** [comment]
The problem occurs when zero-width annotations exist between two directly adjacent tokens.
