### ISSUE TITLE
Importing same Tagset file twice causes application to crash

### ISSUE THREAD

**Issue by aakashysharma** [webanno/webanno#76]
Steps to recreate

1.Import same tagset file twice, it'd import without showing an error.
2.Navigate to Layers tab in Project settings.
3. Select the layer which is already configured to use the tagset used in step 1.
4. The application crashes.

```
Caused by: javax.persistence.EntityNotFoundException: Unable to find de.tudarmstadt.ukp.clarin.webanno.model.TagSet with id 11
	at org.hibernate.ejb.Ejb3Configuration$Ejb3EntityNotFoundDelegate.handleEntityNotFound(Ejb3Configuration.java:155)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:210)
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:251)
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:148)
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1079)
	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1006)
	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:613)
	at org.hibernate.type.EntityType.resolve(EntityType.java:441)
	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:168)
	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:134)
	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:995)
	at org.hibernate.loader.Loader.doQuery(Loader.java:874)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
	at org.hibernate.loader.Loader.doList(Loader.java:2438)
	at org.hibernate.loader.Loader.doList(Loader.java:2424)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2254)
	at org.hibernate.loader.Loader.list(Loader.java:2249)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:470)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1248)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
	at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:257)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationServiceImpl.listAnnotationFeature(AnnotationServiceImpl.java:676)
	at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy38.listAnnotationFeature(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:480)
	at com.sun.proxy.$Proxy52.listAnnotationFeature(Unknown Source)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectLayersPanel$FeatureSelectionForm$3.load(ProjectLayersPanel.java:1138)
	at de.tudarmstadt.ukp.clarin.webanno.project.page.ProjectLayersPanel$FeatureSelectionForm$3.load(ProjectLayersPanel.java:1)
	at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:124)
	at org.apache.wicket.markup.html.form.AbstractChoice.getChoices(AbstractChoice.java:230)
	at org.apache.wicket.markup.html.form.AbstractChoice.onComponentTagBody(AbstractChoice.java:368)
	at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:71)
	at org.apache.wicket.Component.internalRenderComponent(Component.java:2536)
	... 82 more
```

**Comment by reckart** [comment]
A stack trace would be useful.

**Comment by aakashysharma** [comment]
Strack trace as requested.
[ErrorLog_ImportingTagsetsTwiceCausesCrash.txt](https://github.com/webanno/webanno/files/1434/ErrorLog_ImportingTagsetsTwiceCausesCrash.txt)

**Comment by reckart** [comment]
I've copied the stack trace into your initial comment. Having the relevant part of the trace in the issue helps searching for it later / searching for duplicates.

**Comment by reckart** [comment]
The problem appears to lie with the import. There is a "unique" constraint in the database that prevents importing a tagset with the same name twice into a project (at least if the database was set up correctly). During import, WebAnno should check if there is already a tagset with the name and if yes add a suffix.

For projects, this is handled via `ImportUtil.copyProjectName(RepositoryService, String)`. We need somethings like this also for tagsets and btw. also for constraints. For layers, it is not relevant though, because it is assumed that layer names are globally unique (although that may not be true). If there is already a layer with a name, then the import should just be skipped, possibly a warning should be show in the feedback panel.

Can you please have a look at properly handling duplicate names of tagsets/constraints during import?

**Comment by aakashysharma** [comment]
This causes application to throw error on project and tagset deletion as well.

**Comment by reckart** [comment]
This should be resolved when double-import is prevented in the first place.

**Comment by aakashysharma** [comment]
Came across these lines of code in ProjectTagSetPanel.java

```
    private static void createTagSet(Project project, User user, TagSet importedTagSet,
            AnnotationService aAnnotationService)
        throws IOException
    {
        if (aAnnotationService.existsTagSet(importedTagSet.getName(), project)) {
            aAnnotationService.removeTagSet(aAnnotationService.getTagSet(importedTagSet.getName(),
                    project));
        }
```

So, it's just overwriting the old tagset however in settings, it's being referred by old tagset ID? Is that causing application to crash? 

Should I modify this approach so that it's renamed not overwritten?

**Comment by aakashysharma** [comment]
Please reopen if approach has to be changed, other than renaming while importing.

**Comment by reckart** [comment]
Removing the old tagset would cause all the features that refer to it to break. The new tagset should be imported under a different name without removing the existing one.

**Comment by reckart** [comment]
The fix should go into 2.3.1 as well.

**Comment by reckart** [comment]
Btw. from user feedback I gather that *replacing* an existing tagset is actually a nice feature. Now, when we upload a new tagset with the same name, we create a "Copy of..." version but then the user has to update all the features. It might be a good idea to have a checkbox during import "Replace existing with same name" that would actually replace an existing tagset with the new one. That would mean replace descriptions, name, etc. and removing all existing tags in the set and replacing them with the new ones.

**Comment by aakashysharma** [comment]
Questions:

The tags in use (from tagset) in project which is to be replaced, would they be affected? I mean, they are referred by [ids], I believe. 

Replacing tagset completely with new tags (which in-turn will generate new ids), would it ruin the work already done in project? 

If we are to replace existing tagset, we have to find all places where it is being referenced(used). Even if maintain the tagset id, do you think tags id would cause issues?

**Comment by reckart** [comment]
Tags have IDs but the only place that refers to tags by their IDs is the tagset. In the CAS they are stored by their name, not by their ID. Thus, nothing needs to be updated except the tagset which is being replaced/updated anyway.

**Comment by aakashysharma** [comment]
Need to change how duplicate tagsets are handled while importing. Need to copy content(tags) instead of creating a new tagset which can cause issues like #170

**Comment by mmev** [comment]
It would be beneficial if WebAnno could ask the user what the user would like to do:
a) copy under a new, custom-given name -- this would be very useful!
b) overwrite tagset with the new one
c) skip importing this tagset (but import all the other stuffs)

Probably there could be a related problem in the behaviour of importing a layer: If you import a layer, it also imports all the tagsets it uses automatically. Probably, the user could decide if the tagsets also should be imported and how (like options a)-c)).

**Comment by reckart** [comment]
Such questions are cumbersome to implement. If a tagset already exists, a new tagset with an appended number should be created - this is the way we handle it for projects and for the moment I see no reason to handle it differently for tagsets. @seyyaw @ChrisBieTUDA

**Comment by seyyaw** [comment]
+1 for appending numbers for duplicate @reckart
