### ISSUE TITLE
"Next page" on curation page does not work

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#789]
When I have checked a sentence and no changes are to made, I need to click on a sentence number to get to another sentence; the "next page" option does not work for this page. On clicking it, it gives this error:

Error: / by zero

**Comment by reckart** [comment]
So far, I am unable to reproduce this. If anybody could provide additional details, it would be great. I'll push this to 3.3.4 and close it if nobody is able to reproduce it.

**Comment by kazukisan** [comment]
"Next page" works fine on my end on curation page on 3.3.x.

**Comment by sudeep307** [comment]
Maybe the issue is with the upload file format? I've uploaded txt files in the line-oriented plain text format. Also, I found that the "next page" option on the curation page doesn't work only when 1 sentence per page is selected; when I choose 2 sentences per page, the next page option works well! 

My version is 3.3.2.

**Comment by reckart** [comment]
Hit this once now - here is the stack trace:

```
2018-01-14 16:42:01 ERROR [admin] CurationPage - Error: / by zero
java.lang.ArithmeticException: / by zero
	at de.tudarmstadt.ukp.clarin.webanno.api.annotation.util.WebAnnoCasUtil.getDisplayWindowBeginningSentenceAddresses(WebAnnoCasUtil.java:603) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.annotation.util.WebAnnoCasUtil.getPreviousDisplayWindowSentenceBeginAddress(WebAnnoCasUtil.java:548) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.api.annotation.model.AnnotatorState.moveToPreviousPage(AnnotatorState.java:281) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.ui.annotation.AnnotationPageBase.actionShowPreviousPage(AnnotationPageBase.java:175) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.ui.curation.page.CurationPage.lambda$12(CurationPage.java:281) ~[classes/:?]
	at de.tudarmstadt.ukp.clarin.webanno.support.lambda.LambdaAjaxLink.onClick(LambdaAjaxLink.java:66) [classes/:?]
	at org.apache.wicket.ajax.markup.html.AjaxLink$1.onEvent(AjaxLink.java:85) [wicket-core-7.8.0.jar:7.8.0]
       ...
```

**Comment by reckart** [comment]
When this happens, the `getPreferences().getWindowSize()` returns 0.

**Comment by reckart** [comment]
Similar to #755 - this happens because the curation preferences do not get properly initialized.
