### ISSUE TITLE
WebAnno does not support DKPro Core elevated types

### ISSUE THREAD

**Issue by reckart** [webanno/webanno#8]
Create an XMI using DKPro Core, e.g. using POS tagger which creates elevated types.

Trying to edit that XMI in WebAnno creates an Exception like

```
Caused by: javax.persistence.NoResultException: No entity found for query
        at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:291)
        at de.tudarmstadt.ukp.clarin.webanno.api.dao.AnnotationServiceImpl.getLayer(AnnotationServiceImpl.java:256)
```

See also the following posts on the mailing list:
- https://groups.google.com/d/msg/webanno-user/6y3kTSHOrP4/AXjQ3kzrAAAJ
- https://groups.google.com/d/msg/webanno-user/2Hn9g7p9fX0/TU3iiDwqLAAJ

---

Old description

```
What steps will reproduce the problem?
1. Create a project with a new layer that can encompass multiple tokens and also cross
the sentence boundary 
2. Let several annotators annotate the project
3. Got to the monitoring site, select the new project and click in the lower left section
on the layer that you created, in order to show the kappa statistics.
4. An Internal Error Page appears in the browser.

What is the expected output? What do you see instead?
Expected: Kappa Statistics
Shown: Internal Error (http://...:18080/webanno-2.0.12/wicket/bookmarkable/org.apache.wicket.markup.html.pages.InternalErrorPage)

What version of the product are you using? On what operating system?
WebAnno: webanno 2.0.12
Server OS: Linux 3.2.0-57-generic x86_64
Tomcat: Apache Tomcat/6.0.35
JVM: 1.6.0_32-b32
Client Browser: Google Chrome Version 39.0.2171.95 (64-bit)

Please provide any additional information below.


```

Original issue reported on code.google.com by `wlsidorenko` on 2015-01-05 11:00:00

**Comment by reckart** [comment]
Agreement calculation has been rewritten from scratch for 3.0.0.

**Comment by reckart** [comment]
Exception from the attached catalina.out:

```
Caused by: javax.persistence.NoResultException: No entity found for query
	at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:291)
	at de.tudarmstadt.ukp.clarin.webanno.api.dao.RepositoryServiceDbData.getAnnotationDocument(RepositoryServiceDbData.java:716)
	at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy39.getAnnotationDocument(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.apache.wicket.proxy.LazyInitProxyFactory$JdkHandler.invoke(LazyInitProxyFactory.java:431)
	at org.apache.wicket.proxy.$Proxy47.getAnnotationDocument(Unknown Source)
	at de.tudarmstadt.ukp.clarin.webanno.monitoring.page.MonitoringPage.updateAgreementTable(MonitoringPage.java:714)
	at de.tudarmstadt.ukp.clarin.webanno.monitoring.page.MonitoringPage.access$1700(MonitoringPage.java:99)
	at de.tudarmstadt.ukp.clarin.webanno.monitoring.page.MonitoringPage$AnnotationTypeSelectionForm$2.onUpdate(MonitoringPage.java:515)
	at org.apache.wicket.ajax.form.AjaxFormComponentUpdatingBehavior.onEvent(AjaxFormComponentUpdatingBehavior.java:157)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:184)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:369)
	... 64 more
```

**Comment by reckart** [comment]
I have diagnosed a similar problem like this:

> The problem is caused by the DKPro Core "elevated types" - the habit that we have UIMA types for certain POS tags, Chunks, Constituents, etc. WebAnno does not support these - it expects that POSes are POSes not NNs and Chunks are Chunks and not VCs etc.
I'll think if/what we can do about this... my feeling is - though - that this is not trivial. The best would if you could import in such a way that these typ-types of POS, Chunk, etc. are not in the files.

If you have been working with data pre-processed using DKPro Core and then imported into WebAnno, it may be the same problem that you have hit.

**Comment by reckart** [comment]
https://github.com/webanno/webanno/pull/1182 should take care the the application doesn't crash when it encounters DKPro Core elevated types. However, it doesn't actually support tag-to-type mappings. Any new annotations on a layer will always have the layer type. When the tag value on imported elevated types are changed, the annotation type does not change.
